TRUNCATE TABLE Afip;

LOAD DATA LOCAL INFILE 'data/Afip.csv' 
INTO TABLE Afip
CHARACTER SET UTF8
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(@cuit)
SET cuit=@cuit, version=0;