TRUNCATE TABLE Province;

LOAD DATA LOCAL INFILE 'data/Province.csv' 
INTO TABLE Province
CHARACTER SET UTF8
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(@id, @name)
SET id=@id, name=@name, version=0;
